version: '3.8'
services:
  spring_boot:
    image: spring_boot_image:latest
    ports:
      - "8080:8080"
  data_base:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret-pw
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    ports:
        - "3306:3306"